### ISSUE TITLE
ScanNet dataset preparation

### ISSUE THREAD

**Issue by Trainingzy** [CVMI-Lab/DODA#1]
Thanks for your great work!

Can you release the scripts for preparing ScanNet? Your preparation seems to be different from that of [PointGroup](https://github.com/dvlab-research/PointGroup/blob/master/dataset/scannetv2/prepare_data_inst.py). I think you do not use [label remapper](https://github.com/dvlab-research/PointGroup/blob/a41c2cd22808861f0d4986b2825875c10bb661e5/dataset/scannetv2/prepare_data_inst.py#L12) during preparation.

**Comment by Dingry** [comment]
Hi, I use the label remapper exactly the same as the PointGroup. I just do not use the color and instance labels stored in the prepared ScanNet data.

**Comment by Trainingzy** [comment]
Thanks for your quick reply. 
PointGroup converts all labels to 0-19, while [your label mapper](https://github.com/CVMI-Lab/DODA/blob/master/dataset/class_mapper/3dfront_2_scannet.json) contains labels larger than 19.

**Comment by Dingry** [comment]
If you mean the label id in ''src", it is the label from 3D-FRONT. The ScanNet label id is in "tar'"

**Comment by Trainingzy** [comment]
oh, I see. Thanks.
