### ISSUE TITLE
Inconsistent voxel scale

### ISSUE THREAD

**Issue by Trainingzy** [CVMI-Lab/DODA#2]
Thanks for your code!

I am new to point clouds processing and I find the voxel scale used in [VSS](https://github.com/CVMI-Lab/DODA/blob/d2c9df562b04c5446a0f174f6921a634724a24a7/dataset/augmentor/augmentor_utils.py#L180) (10) is different from that in [elastic](https://github.com/CVMI-Lab/DODA/blob/d2c9df562b04c5446a0f174f6921a634724a24a7/dataset/augmentor/data_augmentor.py#L172) (50). Will this inconsistency cause some problems?

**Comment by Dingry** [comment]
Hey, it doesn't cause a problem since voxelization in VSS just helps to detect non-object occupied positions as camera candidates. It does not need to be too precise, so a larger voxel size is sufficient for fast processing.

**Comment by Trainingzy** [comment]
Thanks for the reply. I have one more question about voxelization. The voxel size is not fed to the [voxelization function](https://github.com/CVMI-Lab/DODA/blob/d2c9df562b04c5446a0f174f6921a634724a24a7/dataset/dataset.py#L182). How does it know the voxel size?

**Comment by Dingry** [comment]
Hi, the xyz is already scaled by the voxel size in the augmentation stage. https://github.com/CVMI-Lab/DODA/blob/master/dataset/augmentor/data_augmentor.py#L172.

**Comment by Trainingzy** [comment]
Oh, I understand it now. Thanks!
