### ISSUE TITLE
How should I solve this problem？

### ISSUE THREAD

**Issue by liwell24** [CVMI-Lab/DODA#3]
Thanks for your great work！
When I was doing the self-training, the system reported some errors.

******************* Get Pseudo Label Confidence *********************
train:   0%|                                                                                                                                                   | 0/51 [00:00<?, ?it/s]Traceback (most recent call last):
  File "tool/st.py", line 535, in <module>
    main()
  File "tool/st.py", line 529, in main
    train_sampler=train_sampler, best_mIoU=best_mIoU, best_epoch=best_epoch)
  File "tool/st.py", line 360, in train
    rank=rank, dist=dist_train
  File "./util/pseudo_labels_util.py", line 163, in set_pseudo_labels
    thres = get_perclass_thres(cfg, logger, train_loader, model, model_fn, epoch, rank, dist=dist)
  File "./util/pseudo_labels_util.py", line 153, in get_perclass_thres
    thres = get_thres_per_class_on_thres_ratio(cfg, logger, train_loader, model, model_fn, epoch, rank, dist=dist)
  File "./util/pseudo_labels_util.py", line 131, in get_thres_per_class_on_thres_ratio
    cfg, logger, train_loader, model, test_model_fn_st, epoch, rank, dist=dist
  File "./util/pseudo_labels_util.py", line 110, in get_label_confidence
    reduce(lambda x, y: x + y, common_utils.all_gather_object(class_confidence_batch[c][:max_points])))
TypeError: 'float' object is not iterable
Traceback (most recent call last):                                                                                                                                                    
  File "/cloud/env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/cloud/env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/cloud/env/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/cloud/env/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/cloud/env/bin/python3', '-u', 'tool/st.py', '--local_rank=0', '--launcher', 'pytorch', '--cfg_file', 'cfgs/da_front3d_s3dis/spconv_st.yaml', '--weight', 'output/da_front3d_s3dis/spconv/default/ckpt/best_train.pth']' returned non-zero exit status 1

Can you give me some solutions？Looking forward to your reply.

**Comment by Dingry** [comment]
Hi, did you make any modifictaions to the config or code?  Could you post the self-train cmd so that we can check what is the problem?

**Comment by liwell24** [comment]
Yes, I did. My self-train cmd is 
`sh scripts/train.sh 1 st --cfg_file cfgs/da_front3d_s3dis/spconv_st.yaml --weight output/da_front3d_s3dis/spconv/default/ckpt/train_5654.pth`
but i got some errors,

> Traceback (most recent call last):
>   File "./util/config.py", line 60, in merge_new_config
>     yaml_config = yaml.load(f, Loader=yaml.FullLoader)
>   File "/home/featurize/work/.local/lib/python3.7/site-packages/yaml/__init__.py", line 81, in load
>     return loader.get_single_data()
>   File "/home/featurize/work/.local/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
>     node = self.get_single_node()
>   File "/home/featurize/work/.local/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
>     document = self.compose_document()
>   File "/home/featurize/work/.local/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
>     node = self.compose_node(None, None)
>   File "/home/featurize/work/.local/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
>     node = self.compose_mapping_node(anchor)
>   File "/home/featurize/work/.local/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
>     item_value = self.compose_node(node, item_key)
>   File "/home/featurize/work/.local/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
>     node = self.compose_mapping_node(anchor)
>   File "/home/featurize/work/.local/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
>     item_value = self.compose_node(node, item_key)
>   File "/home/featurize/work/.local/lib/python3.7/site-packages/yaml/composer.py", line 82, in compose_node
>     node = self.compose_sequence_node(anchor)
>   File "/home/featurize/work/.local/lib/python3.7/site-packages/yaml/composer.py", line 110, in compose_sequence_node
>     while not self.check_event(SequenceEndEvent):
>   File "/home/featurize/work/.local/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
>     self.current_event = self.state()
>   File "/home/featurize/work/.local/lib/python3.7/site-packages/yaml/parser.py", line 484, in parse_flow_sequence_entry
>     "expected ',' or ']', but got %r" % token.id, token.start_mark)
> yaml.parser.ParserError: while parsing a flow sequence
>   in "cfgs/dataset_cfgs/front3d/front3d_cfg.yaml", line 17, column 16
> expected ',' or ']', but got '<scalar>'
>   in "cfgs/dataset_cfgs/front3d/front3d_cfg.yaml", line 18, column 17

I find “cfgs/dataset_cfgs/front3d/front3d_cfg.yaml” line17 the end of 'Coffee Table' missing a comma，so i added. Then, I didn't change anything else.

**Comment by Dingry** [comment]
Hi, the config error is corrected. Thanks! 
For the self-training error, maybe you can start the process without DDP since only 1 gpu is used. The script is `python tool/st.py xxx`. If the error exists, I will check it later. Thanks!

**Comment by liwell24** [comment]
Thank for your reply. I got other errors.

> ******************* Generating Pseudo Labels *********************
train:   2%|██▋                                                                                                                                         | 1/51 [00:08<06:59,  8.38s/it]Traceback (most recent call last):
  File "tool/st.py", line 535, in <module>
    main()
  File "tool/st.py", line 529, in main
    train_sampler=train_sampler, best_mIoU=best_mIoU, best_epoch=best_epoch)
  File "tool/st.py", line 360, in train
    rank=rank, dist=dist_train
  File "./util/pseudo_labels_util.py", line 167, in set_pseudo_labels
    done=True, dist=dist
  File "./util/pseudo_labels_util.py", line 62, in generate_pseudo_labels
    cfg, batch, train_loader, model, model_fn_st, epoch, pseudo_labels_dir, thres=thres)
  File "./util/pseudo_labels_util.py", line 29, in generate_pseudo_label_batch
    with_crop=cfg.DATA_CONFIG_TAR.DATA_PROCESSOR.get('crop_to_regions', False)
  File "./util/pseudo_labels_util.py", line 17, in forward_test_model
    ret = model_fn(batch, model, epoch, thres=thres, with_crop=with_crop)
  File "./model/unet.py", line 134, in test_model_fn
    weight[confidence_mask] = confidence[confidence_mask]
RuntimeError: shape mismatch: value tensor of shape [830461] cannot be broadcast to indexing result of shape [830459]

**Comment by Dingry** [comment]
I tried with `python3 tool/st.py --cfg_file cfgs/da_front3d_s3dis/spconv_st.yaml --weight output/train_5654.pth` and it works well without errors. Maybe you can clear the output dir or assign a new extra_tag.

**Comment by liwell24** [comment]
I try again, but got  same errors, I searched the Internet, some people say it maybe caused by environment versions. 
 Could you tell me your environment version? 
My environment `python3.7 pytorch1.5 cuda10.2 spconv1.2`

**Comment by liwell24** [comment]
@Dingry Thank you very much! It works well now.
