### ISSUE TITLE
3D front dataset preprocessing script

### ISSUE THREAD

**Issue by msingh27** [CVMI-Lab/DODA#5]
Hi, 

Thanks a lot for open-sourcing your exciting work!

I was wondering if you can share the preprocessing script (point cloud sampling + label assignment script) for 3dFront?

Is there a way to obtain instance id information (along with semantic category) for each point in the point cloud in the processed dataset "density1250.zip".

It would be great if you could explain the meaning of the values in points[:, 3:6] as mentioned in code below 
https://github.com/CVMI-Lab/DODA/blob/b5f694202cdff94c6e013b2b5b1bc8ddfd22f0c9/dataset/front3d.py#L46

**Comment by Dingry** [comment]
Hi, you can refer to the this link for 3D-FRONT processing: https://github.com/3D-FRONT-FUTURE/3D-FRONT-ToolBox/tree/master. The point cloud sampling is based on [CloudCompare](https://www.cloudcompare.org/) with density 1250. The label taxtonomy is provided in the suppl. file. We'll make the pre-processing scripts public once we've organized it.

points[:, 3:6] denotes the coordinations, which is stored in the column 0-3 in points array.

**Comment by CurryYuan** [comment]
Hi @Dingry ,

Is there any progress on the preprocessing script?
